### ISSUE TITLE
Pressing the treat button as a first move crashes

### ISSUE THREAD

**Issue by nirajlmali** [hoangj21/Pandemic#15]
After starting the game with 2 players, I pressed "Treat" and the game crashed. When I tried to select a City there wasn't a response but the "Move" button tells me to select a city.

Most buttons are also unresponsive.

**Comment by nirajlmali** [comment]
Crashed after finishing first turn as well.

**Comment by schibel21** [comment]
Thank you for noticing this issue! We are working to resolve this issue as soon as possible.
