### ISSUE TITLE
Started game as The Scientist role...

### ISSUE THREAD

**Issue by lafave20** [hoangj21/Pandemic#20]
Started game as The Scientist role... I was unable to select a city. I tried to pass. This led to the app crashing.

**Comment by lafave20** [comment]
Same was true in the Medic role. I was unable to select a city or pass.

**Comment by lafave20** [comment]
Oops. Figured out how to move. Previously thought you had to select the cards on the left not the small dots on the map. It works though

**Comment by schibel21** [comment]
Thank you for giving feedback! I'm glad you figured out what was going on because it is a very confusing game!
