### ISSUE TITLE
Missing status information on smaller tablet

### ISSUE THREAD

**Issue by kearneyk-up** [hoangj21/Pandemic#23]
When I launch the game on a pixel C, there is a pane at the right hand side of the screen displaying various bits of status information (current turn, moves left, etc).
If the game is launched on a nexus 9, the status pane is missing.

**Comment by schibel21** [comment]
Thank you for noticing this! We realize that this game has not been adapted for the Nexus 9 and will only be playable on the Pixel C. We are very sorry for an inconvenience when playing the game.
