### ISSUE TITLE
Player dot hidden when in the same city as AI

### ISSUE THREAD

**Issue by kearneyk-up** [hoangj21/Pandemic#27]
On the first turn, the player and the AI both start out in Atlanta. The AI's dot completely covers the player's dot, making it impossible to see from the map where the player is.

Steps to reproduce:
1. Start a new game.
2. Notice that the status display says that the player is in Atlanta.
3. Try to find a blue dot on the map.

Expected behavior:
Blue dot is found somewhere in the vicinity of Atlanta.

Actual behavior:
Blue dot is cowardly hiding behind the AI's dot.

**Comment by schibel21** [comment]
Thank you for noticing this issue! Yes we do realize that the blue dot cowers behind the magenta dot in fear, but it is just the rising underdog as it comes out of nowhere to save the day! You are the super hero of this story!
