### ISSUE TITLE
Unlimited Moves

### ISSUE THREAD

**Issue by liao21** [hoangj21/Pandemic#3]
There appears to be unlimited moves for the first player. 

User may press move and the toast will say there are 4 moves left. After clicking on an adjacent city, the red dot would move there. After clicking the move button again, the toast said there were 3 moves left. After repeating the previous steps (click the move button, click an adjacent city, click the move button again), the toast still said there were 3 moves left. I can't seem to run out of moves, so I can't end my turn or the game. 

Maybe the toast is not updating the actual number of remaining moves. 

Best of luck, 

Hayden

**Comment by schibel21** [comment]
Thank you for noticing this issue! We have fixed this issue and now the move button works properly and shows the correct amount of moves left and moves on to the next player.
