### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by meremarcinko** [hoangj21/Pandemic#9]
Im not sure if the buttons are working correctly, when I try to tap one of the buttons, it comes up with the statement that I am touching the GUI or that I only have a certain amount of moves left. But I dont really see a change if I have played a move.

I think when you tap too much on the GUI the program crashes

**Comment by schibel21** [comment]
Thank you for noticing this issue! We have resolved this issue and now the player can tell how many moves they have left and if the action they have pressed has been addressed in the game.
